// src/components/Header.vue
<script setup lang="ts">
import { onMounted } from "vue";
import { useBrowserLocation, useShare } from "@vueuse/core";
import { useStore } from "@nanostores/vue";
import { spotifyToken as st, resetSpotifyToken } from "../store/spotifyToken";
import { user as u, updateUser } from "../store/user";
import TimeRangeSelector from "./TimeRangeSelector.vue";

const spotifyToken = useStore(st);
const location = useBrowserLocation();
const { share, isSupported } = useShare();

const user = useStore(u);

const logOut = () => {
  resetSpotifyToken();
  window.location.href = "login";
};

const shareURL = () => {
  const url = `${location.value.origin}/login-callback#access_token=${spotifyToken.value}&token_type=Bearer&expires_in=3600`;
  if (isSupported) {
    share({
      title: "top-for-spotify",
      text: `${user.value?.display_name}'s Spotify stats`,
      url,
    });
  } else {
    navigator.clipboard.writeText(url);
    window.alert("URL copied to clipboard");
  }
};

onMounted(updateUser);
</script>

<template>
  <div
    class="p-4 sm:p-8 dark:bg-black border-b-2 border-gray-300 dark:border-gray-700 w-full flex flex-wrap gap-y-4 justify-between items-center fixed z-10 bg-white"
  >
    <h1 class="text-5xl font-bold">Top for Spotify</h1>
    <div class="flex items-center gap-x-2">
      <TimeRangeSelector />
    </div>
    <div class="flex items-center gap-x-8">
      <img
        class="h-12 rounded-xl shadow-lg hidden sm:block"
        :src="user?.images[0].url"
      />
      <button class="scale-200 i-feather-share" @click="shareURL" />
      <button class="scale-200 i-feather-log-out" @click="logOut" />
    </div>
  </div>
</template>

// src/lib/Header.svelte
<script lang="ts">
	import TimeRangeSelector from '$lib/TimeRangeSelector.svelte';
	import UserImage from '$lib/UserImage.svelte';
	import LogoutButton from '$lib/LogoutButton.svelte';
	import ShareButton from '$lib/ShareButton.svelte';
	import IconShare from '~icons/feather/share';
	import IconLogOut from '~icons/feather/log-out';
	import { page } from '$app/stores';

	const isLoggedIn = $page.url.pathname === '/me';
</script>

<div
	class="flex flex-wrap justify-between items-center gap-4 p-4 fixed z-10 bg-white dark:bg-black w-full border-b-2 border-gray-200 dark:border-gray-700"
>
	<div>
		{#if isLoggedIn}
			<TimeRangeSelector />
		{/if}
	</div>

	<h1 class="text-3xl font-bold hidden sm:block">Top for Spotify</h1>

	<div class="flex gap-4">
		{#if isLoggedIn}
			<UserImage />
			<ShareButton>
				<IconShare class="h-6" />
			</ShareButton>
			<LogoutButton>
				<IconLogOut class="h-6" />
			</LogoutButton>
		{/if}
	</div>
</div>
