// pages/me.vue
<script setup lang="ts">
import { getUser } from '~/spotify'
import type { User } from '~/types'

const router = useRouter()

const user = ref<User>()
const updateUser = () => getUser().then(u => user.value = u)

onMounted(() => {
  updateUser().then(() => {
    // if token has expired
    if ((user.value as any).error.status === 401)
      router.push('/login')
  })
})
</script>

<template>
  <Header></Header>

  <main flex flex-col gap-y-8 text-white mt-44 sm:mt-24 sm:p-8>
    <Obscurity></Obscurity>
    <Mood></Mood>
    <Genres></Genres>
    <Artists></Artists>
    <Tracks></Tracks>
  </main>

  <Footer></Footer>
</template>

// src/routes/me.svelte
<script lang="ts">
	import Header from '$lib/Header.svelte';
	import Obscurity from '$lib/Obscurity.svelte';
	import Mood from '$lib/Mood.svelte';
	import Genres from '$lib/Genres.svelte';
	import Artists from '$lib/Artists.svelte';
	import Tracks from '$lib/Tracks.svelte';
</script>

<Header />

<main class="max-w-5xl flex flex-col gap-y-8 px-8 mt-32">
	<Obscurity />
	<Mood />
	<Genres />
	<Artists />
	<Tracks />
</main>
