// src/components/Tracks.svelte
<script lang="ts">
  import Box from "./Box.svelte";
  import { tracks } from "../stores/tracks";
</script>

{#await $tracks then tracks}
  <Box
    className="flex flex-col gap-y-16 bg-gradient-to-r from-pink-400 via-blue-500 to-green-500 font-bold uppercase"
  >
    <h2 class="text-5xl sm:text-7xl text-white">Tracks</h2>
    <div class="grid grid-cols-1 sm:grid-cols-3 gap-4 sm:gap-y-16">
      {#each tracks as track, i}
        <figure class="rounded-2xl shadow-lg bg-white dark:bg-black">
          <img
            class="object-cover h-48 w-96 rounded-2xl p-1"
            src={track.imageURL}
            alt={track.name}
          />
          <figcaption class="text-black dark:text-white mx-4 my-2">
            {i + 1}. {track.name}
          </figcaption>
        </figure>
      {/each}
    </div>
  </Box>
{/await}

// components/Tracks.vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { getTracks } from '~/spotify'
import { useTimeRangeStore } from '~/stores/timeRange'
import type { CardElement } from '~/types'

const timeRange = useTimeRangeStore()

const { t } = useI18n()

const tracks = ref<CardElement[]>()
const updateTracks = () =>
  getTracks(timeRange.timeRange).then(t => tracks.value = t)

onMounted(updateTracks)
watch(timeRange, updateTracks)
</script>

<template>
  <div box flex flex-col gap-y-16 bg-gradient-to-r from-pink-400 via-blue-500 to-green-500 font-bold uppercase>
    <h2 text-5xl sm:text-7xl>
      {{ t('tracks') }}
    </h2>
    <div grid grid-cols-1 sm:grid-cols-3 gap-4 sm:gap-y-16>
      <figure v-for="(track, index) in tracks" :key="index" rounded-2xl shadow-lg bg-white dark:bg-black>
        <img object-cover h-48 w-96 rounded-2xl p-1 :src="track.imageURL">
        <figcaption text-black dark:text-white mx-4 my-2>
          {{ index + 1 }}. {{ track.name }}
        </figcaption>
      </figure>
    </div>
  </div>
</template>
