// src/components/Artists.svelte
<script lang="ts">
  import Box from "./Box.svelte";
  import { artists } from "../stores/artists";
</script>

<Box
  className="flex flex-col gap-y-16 bg-gradient-to-r from-yellow-400 to-pink-500 font-bold uppercase"
>
  <h2 class="text-5xl sm:text-7xl text-white">Artists</h2>
  <div class="grid grid-cols-1 sm:grid-cols-3 gap-4 sm:gap-y-16">
    {#each $artists as artist, i}
      <figure class="rounded-2xl shadow-lg bg-white dark:bg-black">
        <img
          class="object-cover h-48 w-96 rounded-2xl p-1"
          src={artist.imageURL}
          alt={artist.name}
        />
        <figcaption class="text-black dark:text-white mx-4 my-2">
          {i + 1}. {artist.name}
        </figcaption>
      </figure>
    {/each}
  </div>
</Box>

// src/components/Artists.vue
<script setup lang="ts">
import { useStore } from "@nanostores/vue";
import { artists as a } from "../store/artists";

const artists = useStore(a);
</script>

<template>
  <div
    class="box flex flex-col gap-y-16 bg-gradient-to-r from-yellow-400 to-pink-500 font-bold uppercase"
  >
    <h2 class="text-5xl sm:text-7xl text-white">Artists</h2>
    <div class="grid grid-cols-1 sm:grid-cols-3 gap-4 sm:gap-y-16">
      <figure
        v-for="(artist, index) in artists"
        :key="index"
        class="rounded-2xl shadow-lg bg-white dark:bg-black"
      >
        <img
          class="object-cover h-48 w-96 rounded-2xl p-1"
          :src="artist.imageURL"
        />
        <figcaption class="text-black dark:text-white mx-4 my-2">
          {{ index + 1 }}. {{ artist.name }}
        </figcaption>
      </figure>
    </div>
  </div>
</template>
