// src/lib/Footer.svelte
<script lang="ts">
	import IconGithub from '~icons/feather/github';
</script>

<footer class="flex flex-col sm:flex-row flex-wrap sm:divide-x items-center mb-4">
	<div class="px-2">MIT Licensed</div>
	<div class="px-2">© 2021-2022 Manuel Quarneti</div>
	<div class="px-2">
		<a class="block" href="https://github.com/mq1/top-for-spotify">
			<IconGithub class="h-4 sm:h-6" />
		</a>
	</div>
</footer>

// src/components/Footer.vue
<template>
  <footer class="flex justify-center divide-x-2">
    <div class="px-2 flex items-center">
      MIT Licensed
    </div>
    <div class="px-2 flex items-center">
      © 2021 Manuel Quarneti
    </div>
    <div class="px-2 flex items-center">
      Hosted on Netlify
    </div>
    <a class="px-2 flex items-center" href="https://github.com/mq1/top-for-spotify">
      <carbon-logo-github />
    </a>
  </footer>
</template>
