// src/components/Genres.vue
<script setup lang="ts">
import { ref, onMounted, watch } from "vue";
import { useStore } from "@nanostores/vue";
import { timeRange as tr } from "../store/timeRange";
import { getGenres } from "../spotify";

const timeRange = useStore(tr);

const genres = ref<string[]>();
const updateGenres = () =>
  getGenres(timeRange.value).then((g) => (genres.value = g));

onMounted(updateGenres);
watch(timeRange, updateGenres);
</script>

<template>
  <div
    class="box flex flex-col gap-y-16 bg-gradient-to-r from-green-400 to-blue-500 font-bold text-white uppercase"
  >
    <h2 class="text-5xl sm:text-7xl">Genres</h2>
    <ol class="list-decimal text-left leading-loose text-2xl ml-8">
      <li v-for="genre in genres" :key="genre">
        {{ genre }}
      </li>
    </ol>
  </div>
</template>

// src/components/Genres.svelte
<script lang="ts">
  import Box from "./Box.svelte";
  import { genres } from "../stores/genres";
</script>

{#await $genres then genres}
  <Box
    className="flex flex-col gap-y-16 bg-gradient-to-r from-green-400 to-blue-500 font-bold text-white uppercase"
  >
    <h2 class="text-5xl sm:text-7xl">Genres</h2>
    <ol class="list-decimal text-left leading-loose text-2xl ml-8">
      {#each genres as genre}
        <li>{genre}</li>
      {/each}
    </ol>
  </Box>
{/await}
