// components/Genres.vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { getGenres } from '~/spotify'
import { useTimeRangeStore } from '~/stores/timeRange'

const timeRange = useTimeRangeStore()

const { t } = useI18n()

const genres = ref<string[]>()
const updateGenres = () =>
  getGenres(timeRange.timeRange).then(g => genres.value = g)

onMounted(updateGenres)
watch(timeRange, updateGenres)
</script>

<template>
  <div box flex flex-col gap-y-16 bg-gradient-to-r from-green-400 to-blue-500 font-bold uppercase>
    <h2 text-5xl sm:text-7xl>
      {{ t('genres') }}
    </h2>
    <ol list-decimal text-left leading-loose text-2xl ml-8>
      <li v-for="genre in genres" :key="genre">
        {{ genre }}
      </li>
    </ol>
  </div>
</template>

// src/components/Genres.svelte
<script lang="ts">
  import Box from "./Box.svelte";
  import { genres } from "../stores/genres";
</script>

{#await $genres then genres}
  <Box
    className="flex flex-col gap-y-16 bg-gradient-to-r from-green-400 to-blue-500 font-bold text-white uppercase"
  >
    <h2 class="text-5xl sm:text-7xl">Genres</h2>
    <ol class="list-decimal text-left leading-loose text-2xl ml-8">
      {#each genres as genre}
        <li>{genre}</li>
      {/each}
    </ol>
  </Box>
{/await}
