// components/Obscurity.vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { getObscurityRating } from '~/spotify'
import { useTimeRangeStore } from '~/stores/timeRange'

const timeRange = useTimeRangeStore()

const { t } = useI18n()

const obscurityRating = ref<string | number>('?')
const updateObscurityRating = () =>
  getObscurityRating(timeRange.timeRange).then(r => obscurityRating.value = r)

onMounted(updateObscurityRating)
watch(timeRange, updateObscurityRating)
</script>

<template>
  <div box flex flex-col gap-y-8 bg-black font-bold>
    <h2 text-5xl sm:text-7xl uppercase>
      {{ t('obscurity') }}
    </h2>
    <div text-7xl sm:text-9xl>
      {{ obscurityRating }} %
    </div>
  </div>
</template>

// src/components/Obscurity.svelte
<script lang="ts">
  import Box from "./Box.svelte";
  import { obscurity } from "../stores/obscurity";
</script>

{#await $obscurity then obscurity}
  <Box className="flex flex-col gap-y-8 bg-black font-bold text-white">
    <h2 class="text-5xl sm:text-7xl uppercase">Obscurity</h2>
    <div class="text-7xl sm:text-9xl">{obscurity} %</div>
  </Box>
{/await}
