// src/components/ShareButton.svelte
<script lang="ts">
  import { user } from "../stores/user";
  import { spotifyToken } from "../stores/spotifyToken";

  const shareURL = () => {
    const url = `${location.origin}/me#access_token=${$spotifyToken}&token_type=Bearer&expires_in=3600`;
    if (navigator.share) {
      navigator.share({
        title: "top-for-spotify",
        text: `${$user.display_name}'s Spotify stats`,
        url,
      });
    } else {
      navigator.clipboard.writeText(url);
      window.alert("URL copied to clipboard");
    }
  };
</script>

<button on:click={shareURL}>
  <slot />
</button>

// src/components/ShareButton.vue
<script setup lang="ts">
import { useBrowserLocation, useShare } from "@vueuse/core";
import { useStore } from "@nanostores/vue";
import { user as u } from "../store/user";
import { spotifyToken as st } from "../store/spotifyToken";

const user = useStore(u);
const spotifyToken = useStore(st);

const location = useBrowserLocation();
const { share, isSupported } = useShare();

const shareURL = () => {
  const url = `${location.value.origin}/me#access_token=${spotifyToken.value}&token_type=Bearer&expires_in=3600`;
  if (isSupported) {
    share({
      title: "top-for-spotify",
      text: `${user.value?.display_name}'s Spotify stats`,
      url,
    });
  } else {
    navigator.clipboard.writeText(url);
    window.alert("URL copied to clipboard");
  }
};
</script>

<template>
  <button @click="shareURL">
    <slot></slot>
  </button>
</template>
